## This configuration was generated by terraform-provider-oci

resource oci_core_instance export_ap1 {
  availability_config {
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = data.oci_identity_availability_domain.export_TGjA-AD-1.name
  compartment_id      = var.compartment_ocid
  create_vnic_details {
    assign_public_ip = "false"
    display_name = "ap1"
    hostname_label = "ap1"
    nsg_ids = [
      oci_core_network_security_group.export_Network-Security-Group-for-AP.id,
    ]
    private_ip             = var.ap1_ip_address
    # skip_source_dest_check = "true"
    subnet_id              = oci_core_subnet.export_PublicSubnet.id
  }
  display_name = "ap1"
  fault_domain = "FAULT-DOMAIN-1"
  metadata = {
    ssh_authorized_keys = tls_private_key.key.public_key_openssh
    user_data           = base64encode(file("./cloud-init.tpl"))
  }
  shape = "VM.Standard.E3.Flex"
  shape_config {
    memory_in_gbs = "16"
    ocpus         = "1"
  }
  source_details {
    source_id   = var.export_ap1_source_image_id[var.region]
    source_type = "image"
    # boot_volume_size_in_gbs = "50"
  }
  state = "RUNNING"
}
resource oci_core_volume_attachment export_volumeattachment20201109223049 {
  attachment_type = "iscsi"
  display_name                        = "volumeattachment20201109223049"
  instance_id                         = oci_core_instance.export_ap1.id
  is_pv_encryption_in_transit_enabled = "false"
  is_read_only                        = "false"
  volume_id = oci_core_volume.export_db01v.id
}
resource oci_core_volume export_db01v {
  availability_domain = data.oci_identity_availability_domain.export_TGjA-AD-1.name
  compartment_id      = var.compartment_ocid
  display_name = "db01v"
  is_auto_tune_enabled = "false"
  size_in_gbs = "50"
  vpus_per_gb = "10"
}
