## This configuration was generated by terraform-provider-oci

resource oci_mysql_mysql_db_system export_MySQL1 {
  admin_password      = var.mysql_password
  admin_username      = "admin"
  availability_domain = data.oci_identity_availability_domain.export_TGjA-AD-1.name
  backup_policy {
    #defined_tags = <<Optional value not found in discovery>>
    is_enabled        = "true"
    retention_in_days = "7"
    window_start_time = "00:00"
  }
  compartment_id          = var.compartment_ocid
  configuration_id        = var.mysql_configuration_id
  data_storage_size_in_gb = "50"
  display_name = "MySQL1"
  fault_domain = "FAULT-DOMAIN-1"
  hostname_label = "mysql1"
  maintenance {
    window_start_time = "WEDNESDAY 04:22"
  }
#  mysql_version = "8.0.22-u2-cloud"
  port          = "3306"
  port_x        = "33060"
  shape_name    = "VM.Standard.E2.1"
  state     = "ACTIVE"
  subnet_id = oci_core_subnet.export_PrivateSubnet.id

  lifecycle {
    ignore_changes = [admin_password, admin_username]
  }
}
